### ISSUE TITLE
Set specific workspace to hotkey

### ISSUE THREAD

**Issue by jsmorabito** [nothingislost/obsidian-workspaces-plus#21]
also if workspaces could be opened by commands then they could be added to [cMenu](https://github.com/chetachiezikeuzor/cMenu-Plugin) 👀

**Comment by nothingislost** [comment]
Any thoughts on what this would look like, UX wise? Since workspace names aren't static, this could get a bit challenging.

Would you bind a hotkey to a specific workspace name? If that workspace was deleted or renamed, what would be the behavior?

Perhaps we also keep in mind the drag to reorder request and start adding a specific workspace number to each workspace and then assign the hotkey to a workspace number?

Open to suggestions.

**Comment by jsmorabito** [comment]
So something like this maybe?

1. create workspace "my workspace"
- "my workspace" is assigned UID
- "my workspace" is added to hotkeys menu
2. assign [any hotkey] to "my workspace"
- hotkey opens workspace via UID
3. delete "my workspace"
- "my workspace" removed from hotkeys menu and hotkey is unbound

And theoretically this UIDs could be used to order the workspaces

**Comment by nothingislost** [comment]
This plugin is pretty close to the functionality being discussed https://github.com/Vinzent03/obsidian-hotkeys-for-specific-files

The author plugins into the file rename and delete events and updates or removes his hotkey commands accordingly. The emitted events provide the context needed in terms of old name -> new name.

Workspace changes like rename and delete do not currently emit events but I should be able to patch the build in commands to include them.

**Comment by jsmorabito** [comment]
closed via 0.3.0
